# Base configs
baseurl: "https://piotrbrytan.github.io/photography"
# baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Photography by Piotr Brytan"
subtitle: "See the world through my eyes!"
author: "Piotr Brytan"
header:
 title: "Photography"
 subtitle: "by Piotr Brytan"
footer:
 name: "Hey there, my name is Piotr"
 bio: "I am a amateur photographer from Poland."
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork this repo on github</a>"
web_design: "AJ"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  # twitter: ""
  # instagram: ""
  # dribbble: ""
  linkedin: "https://www.linkedin.com/in/piotr-brytan-3a2b06186/"
  github: "https://github.com/piotrbrytan"
